name: Backend CI

on:

  pull_request:
    paths:
      - "backend/**"

  workflow_dispatch:

jobs:

  build:

    uses: ./.github/workflows/reusable-build.yml

  backend-test:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - run: pip install -r requirements.txt

      - run: docker build -t backend:test .